server:
  port: 0
  servlet:
    context-path: /

openapi:
  service:
    title: user-service doc #title that you will want to display in the swagger ui
    version: 1.0.0
    url: http://localhost:9000 #api gateway url

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/e_commerce_userDb
    username: root
    password: Sedat1998
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8999/eureka/
    enabled: true